### PR TITLE
Remove enter from counted characters

### LINKED ISSUE #4: Refine support for Unicode characters
Either here or add a follow up: this might not work with other languages which we may easily support (as not detect non-word characters):

Selection_049

related fix in mentions: https://github.com/ckeditor/ckeditor5-mention/pull/71/files#diff-1684a608a7129dc20f38e3655d982678R548

_Originally posted by @jodator in https://github.com/ckeditor/ckeditor5-word-count/pull/2#discussion_r297601542

### LINKED ISSUE #5: The enter should not be counted as a character
Right now the newline is used to denote blocks and inline elements.

As @msamsel noticed it shouldn't count as a character:

Peek 2019-06-28 15-51

### LINKED ISSUE #2570: Refine support for Unicode characters
Either here or add a follow up: this might not work with other languages which we may easily support (as not detect non-word characters):

Selection_049

related fix in mentions: https://github.com/ckeditor/ckeditor5-mention/pull/71/files#diff-1684a608a7129dc20f38e3655d982678R548

_Originally posted by @jodator in https://github.com/ckeditor/ckeditor5-word-count/pull/2#discussion_r297601542

### LINKED ISSUE #2574: The enter should not be counted as a character
Right now the newline is used to denote blocks and inline elements.

As @msamsel noticed it shouldn't count as a character:

Peek 2019-06-28 15-51

### PR DESCRIPTION
**Pull request by msamsel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Improve words recognition, remove enter from counted characters. Closes ckeditor/ckeditor5#2570. Closes ckeditor/ckeditor5#2574.

---

### Additional information

* PR requires ckeditor/ckeditor5-utils#292

### CODE REVIEW

**Review by Mgsy — APPROVED** [review]
LGTM 👍

File: src/wordcount.js [hunk 1]
```diff
@@ -227,9 +228,14 @@ export default class WordCount extends Plugin {
 	_calculateWordsAndCharacters() {
 		const txt = modelElementToPlainText( this.editor.model.document.getRoot() );
 
-		this.characters = txt.length;
+		this.characters = txt.replace( /\n/g, '' ).length;
 
-		this.words = ( txt.match( /[_a-zA-Z0-9À-ž]+/gu ) || [] ).length;
+		const wordsMatch = featureDetection.isUnicodePropertySupported ?
+			txt.match( new RegExp( '[\\p{L}\\p{N}\\p{M}\\p{Pd}\\p{Pc}]+', 'gu' ) ) :
+			/* istanbul ignore next */
```
Comment (jodator) [inline src/wordcount.js]: Nope :D

You can try and test it: https://github.com/ckeditor/ckeditor5-mention/blob/e8d7d1bc018d3ceeee347dfe7c400c3c2c154c5c/tests/mentionui.js#L448.

Then add also tests for such characters and skip if not supported (we get coverage from Chrome) - https://github.com/ckeditor/ckeditor5-mention/blob/e8d7d1bc018d3ceeee347dfe7c400c3c2c154c5c/tests/mentionui.js#L837

Comment (jodator) [reply src/wordcount.js]: Oh, I see that you've done the second step already for skipping tests.

File: src/wordcount.js [hunk 2]
```diff
@@ -227,9 +228,14 @@ export default class WordCount extends Plugin {
 	_calculateWordsAndCharacters() {
 		const txt = modelElementToPlainText( this.editor.model.document.getRoot() );
 
-		this.characters = txt.length;
+		this.characters = txt.replace( /\n/g, '' ).length;
 
-		this.words = ( txt.match( /[_a-zA-Z0-9À-ž]+/gu ) || [] ).length;
+		const wordsMatch = featureDetection.isUnicodePropertySupported ?
+			txt.match( new RegExp( '[\\p{L}\\p{N}\\p{M}\\p{Pd}\\p{Pc}]+', 'gu' ) ) :
```
Comment (jodator) [inline src/wordcount.js]: Maybe we could add what those groups are? I almost got those categories right (4 of 5) but I was reading them when doing mentions. Others might not remember/know them too well ;)

**Review by jodator — CHANGES_REQUESTED** [review]
Some minor docs improvement are needed + change in related PR is awaiting.

Also, one more tests rather than ignoring coverage :)

File: src/wordcount.js [hunk 3]
```diff
@@ -229,9 +230,19 @@ export default class WordCount extends Plugin {
...
-		this.words = ( txt.match( /[_a-zA-Z0-9À-ž]+/gu ) || [] ).length;
+		// Groups:
+		// {L} - Any kind of letter from any language.
+		// {N} - Any kind of numeric character in any script.
+		// {M} - A character intended to be combined with another character (e.g. accents, umlauts, enclosing boxes, etc.).
+		// {Pd} - Any kind of hyphen or dash.
+		// {Pc} - A punctuation character such as an underscore that connects words.
+		const wordsMatch = regExpFeatureDetection.isUnicodePropertySupported ?
+			txt.match( new RegExp( '[\\p{L}\\p{N}\\p{M}\\p{Pd}\\p{Pc}]+', 'gu' ) ) :
+			txt.match( /[_\-a-zA-Z0-9À-ž]+/gu );
```
Comment (jodator) [inline src/wordcount.js]: Sorry I've missed that earlier...

I got mixed feelings about this ternary - there are two types of RegExp creation where one would be sufficient as we do not create pattern on the fly we could use the latter `/foo/` and not the constructor one but either one will be OK.

The second thing is that then we could move the regexp choosing to a variable:

```js
const wordsMatch = txt.match( matchRegExp ) || []; // also \\ [] can be moved here.
```

**Review by jodator — CHANGES_REQUESTED** [review]
Last minor change.

Sorry for missing this previous time :crying_cat_face:

File: src/wordcount.js (hunk 3 above)
Comment (jodator) [reply src/wordcount.js]: ps.: I've just found out that ESLint is not allowing Unicode groups in `//` form. So we must string pattern and `new RegExp()`.

Comment (msamsel) [reply src/wordcount.js]: > ps.: I've just found out that ESLint is not allowing Unicode groups in // form. So we must string pattern and new RegExp().

Yeah that's exactly the cases why it's used in this form. Maybe there should be a comment about it, as it isn't clear why we use this form?

Comment (msamsel) [reply src/wordcount.js]: It appears that after reinstall dependencies, the ESLint doesn't mark this literal as invalid expression. So I change it.

File: src/wordcount.js [hunk 4]
```diff
@@ -229,9 +230,22 @@ export default class WordCount extends Plugin {
 	_calculateWordsAndCharacters() {
 		const txt = modelElementToPlainText( this.editor.model.document.getRoot() );
 
-		this.characters = txt.length;
+		this.characters = txt.replace( /\n/g, '' ).length;
```
Comment (Reinmar) [inline src/wordcount.js]: What about `<paragraph>Word</paragraph><paragraph>SecondWord</paragraph>`?

File: src/wordcount.js [hunk 5]
```diff
@@ -229,9 +230,22 @@ export default class WordCount extends Plugin {
...
 
-		this.words = ( txt.match( /[_a-zA-Z0-9À-ž]+/gu ) || [] ).length;
+		// Groups:
+		// {L} - Any kind of letter from any language.
+		// {N} - Any kind of numeric character in any script.
+		// {M} - A character intended to be combined with another character (e.g. accents, umlauts, enclosing boxes, etc.).
+		// {Pd} - Any kind of hyphen or dash.
+		// {Pc} - A punctuation character such as an underscore that connects words.
+		const wordsMatchRegExp = env.features.isRegExpUnicodePropertySupported ?
```
Comment (Reinmar) [inline src/wordcount.js]: This shouldn't be created inside a frequently executed callback. It will affect the performance by taking some time, but, more importantly, by increasing GC pressure.

File: src/wordcount.js [hunk 6]
```diff
@@ -229,9 +230,22 @@ export default class WordCount extends Plugin {
 	_calculateWordsAndCharacters() {
```
Comment (Reinmar) [inline src/wordcount.js]: What if we'll add another type of stats?

File: src/wordcount.js [hunk 7]
```diff
@@ -221,17 +240,17 @@ export default class WordCount extends Plugin {
 
 	/**
 	 * Determines the number of words and characters in the current editor's model and assigns it to {@link #characters} and {@link #words}.
-	 * It also fires {@link #event:update}.
+	 * It also fires an {@link #event:update}.
```
Comment (ma2ciek) [inline src/wordcount.js]:
```suggestion
	 * It also fires the {@link #event:update}.
```

File: src/wordcount.js [hunk 8]
```diff
@@ -104,6 +105,24 @@ export default class WordCount extends Plugin {
 		 * @type {module:ui/view~View}
 		 */
 		this._outputView;
+
+		/**
+		 * The regular expression used to recognize words in the editor's content.
```
Comment (ma2ciek) [inline src/wordcount.js]:
```suggestion
		 * A regular expression used to recognize words in the editor's content.
```
