### PR TITLE
Prevent of destroying undefined word count container

### LINKED ISSUE #16: The Wordcount crash if the wordcount container is not defined
Right now the logic is as follows:

```js
// constructor()
this._config = editor.config.get( 'wordCount' ) || {};
```

```js
// init()
if ( isElement( this._config.container ) ) {
	this._config.container.appendChild( this.wordCountContainer );
}
```

```js
// destroy()
destroy() {
	this._outputView.element.remove();
	this._outputView.destroy();

	super.destroy();
}
```

```js
get wordCountContainer() {
	// ...

	if ( !this._outputView ) {
		this._outputView = new View();
	}

	// ...
}
```

So the `this._outputView` might be undefined in the `destroy()` method and this will end up with the `Cannot read property 'element' of undefined` error.

Ref: https://github.com/ckeditor/ckeditor5-angular/issues/123.

### LINKED ISSUE #2575: The Wordcount crash if the wordcount container is not defined
Right now the logic is as follows:

```js
// constructor()
this._config = editor.config.get( 'wordCount' ) || {};
```

```js
// init()
if ( isElement( this._config.container ) ) {
	this._config.container.appendChild( this.wordCountContainer );
}
```

```js
// destroy()
destroy() {
	this._outputView.element.remove();
	this._outputView.destroy();

	super.destroy();
}
```

```js
get wordCountContainer() {
	// ...

	if ( !this._outputView ) {
		this._outputView = new View();
	}

	// ...
}
```

So the `this._outputView` might be undefined in the `destroy()` method and this will end up with the `Cannot read property 'element' of undefined` error.

Ref: https://github.com/ckeditor/ckeditor5-angular/issues/123.

### PR DESCRIPTION
**Pull request by msamsel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Prevent of destroying undefined word count container. Closes ckeditor/ckeditor5#2575.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Review by ma2ciek — APPROVED** [review]

File: tests/wordcount.js [hunk 1]
```diff
@@ -158,6 +158,23 @@ describe( 'WordCount', () => {
...
+					} )
+						.then( _editor => {
+							editor = _editor;
+						} );
+				} );
+
+				it( 'should not throw an error', () => {
+					return editor.destroy();
+				} );
+			} );
```
Comment (pomek) [inline tests/wordcount.js]: This test scenario could be simplified:

```js
it( 'does not throw any error if the container is not specified', () => {
	return VirtualTestEditor
		.create( {
			plugins: [ WordCount, Paragraph ]
		} )
		.then( editor => {
			return editor.destroy();
		} );
} );
```

The whole `describe()` block could be replaced with the snippet.

Comment (ma2ciek) [reply tests/wordcount.js]: I was thinking about it too. If we have only one test we can simplify it.

Comment (msamsel) [reply tests/wordcount.js]: I just copied logic from above. I simplified the logic as @pomek suggest.

**Review by mlewand — APPROVED** [review]
